In [13]:
from portfolioqtopt.optimization.assets_ import Assets
import numpy as np


prices = np.array([
    [100, 102, 104, 108, 116],
    [10, 10.3, 10.9, 10.27, 10.81],
    [100, 104, 116, 164, 356],
]).T
a = Assets(prices)

In [15]:
a.anual_returns

array([0.16 , 0.081, 2.56 ])

In [17]:
a.average_daily_returns

array([0.03803586, 0.02075865, 0.43497736])

In [18]:
a.normalized_prices_approx

array([0.03448276, 0.01873265, 0.17977528])

In [19]:
a.normalized_prices

array([[0.86206897, 0.92506938, 0.28089888],
       [0.87931034, 0.95282146, 0.29213483],
       [0.89655172, 1.00832562, 0.3258427 ],
       [0.93103448, 0.95004625, 0.46067416],
       [1.        , 1.        , 1.        ]])

In [24]:
from portfolioqtopt.optimization.qubo_factory_ import *

pw = get_pw(6)

b = get_anual_returns_partition(a, pw)
c = expand(a.anual_returns, pw, 1)
np.testing.assert_equal(b, c)

In [29]:
b = get_average_daily_returns_partition_tecnalia(a, pw)
c = expand(a.normalized_prices_approx, pw, 1)
np.testing.assert_equal(b, c)

In [32]:
b = get_average_daily_returns_partition_(a, pw)
c = expand(a.average_daily_returns, pw, 1)
np.testing.assert_equal(b, c)

In [36]:
b = get_normalized_prices_partition(a, pw, 1)
c = expand(a.normalized_prices, pw, 1)
np.testing.assert_equal(b, c)